<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Order_Data_Listing_Page.aspx.cs" Inherits="Intellial_Solutions_Assignment_01.Order_Listing.Order_Data_Listing_Page" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <h1>Orders&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <asp:Button ID="btn_addorder" runat="server" OnClick="btn_addorder_Click" Text="Add Order" />
            </h1>
            <asp:GridView ID="GridView2" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="Customer" DataSourceID="SqlDataSource2" Height="134px" Width="450px">
                <Columns>
                    <asp:BoundField DataField="Customer" HeaderText="Customer" ReadOnly="True" SortExpression="Customer" />
                    <asp:BoundField DataField="Product" HeaderText="Product" SortExpression="Product" />
                    <asp:BoundField DataField="Remarks" HeaderText="Remarks" SortExpression="Remarks" />
                </Columns>
            </asp:GridView>
            <asp:SqlDataSource ID="SqlDataSource2" runat="server" 
                ConnectionString="<%$ ConnectionStrings:ConnectionString %>"
                SelectCommand="SELECT * FROM [Table]" UpdateCommand="UPDATE [Table] Set [Customer]=@Customer, [Product]=@Product, [Remarks]=@Remarks where [Customer]=@Customer" DeleteCommand="DELETE from [Table] where [Customer]=@Customer"></asp:SqlDataSource>
        </div>
    </form>
</body>
</html>
